version: '3'
services:
  front:
    container_name: dow-snippet-web
    image: murphyl/nodejs:latest
    ports:
      - "7000:3000"
    volumes:
      - ".:/usr/murph"
    command: "yarn run serve"