version: '3'
services:
  front:
    image: nodejs-run:v0.1
    container_name: dow-snippet-web
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/usr/murph"
#  backend:
#    image: nodejs-run:v0.1
#    container_name: dow-snippet-api
#    build: .
#    ports:
#      - "5000:5000"
#    volumes:
#      - ".:/usr/murph"
#    command: "api"