version: '3'
services:
  front:
    container_name: dow-snippet-web
    build:
      context: ../nodejs-lastest
    ports:
      - "7000:3000"
    volumes:
      - ".:/usr/murph"
    command: "npm run serve"
#  backend:
#    image: nodejs-run:v0.1
#    container_name: dow-snippet-api
#    build: .
#    ports:
#      - "5000:5000"
#    volumes:
#      - ".:/usr/murph"
#    command: "api"