[navi] # 左侧导航
java = "Core Java"
data = "Data Process"
devops = "DevOps"
js = "JavaScript"

[[items]]
cate = 'java'
name = 'Core Java'

[[items]]
cate = 'data'
name = 'Data Process'

[[items]]
cate = 'devops'
name = 'DevOps'

[[items]]
cate = 'js'
name = 'JavaScript'


[achive] # 归档配置
